name: Linting
on: [pull_request]

jobs:
  eslint-review:
    name: runner / eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # BẮT BUỘC để bot có quyền comment vào PR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint with Reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review # Comment trực tiếp vào dòng code trong PR
          filter_mode: added # Chỉ comment vào các dòng code mới sửa đổi trong PR
          eslint_flags: "." # Thư mục chứa code cần quét
